### ISSUE TITLE
Use Base64 images

### ISSUE THREAD

**Issue by PySimpleGUI** [israel-dryer/Media-Player#1]
I recommend always using Base64 images so your distribution can be a single file.  This is AMAZING looking!

**Comment by PySimpleGUI** [comment]
I'm doing this now if you want to wait.....

**Comment by israel-dryer** [comment]
I ended up doing this. The only caveat I see is that converting and working with Base64 is not necessarily 'beginner' friendly. It makes the app portable, but portability is not always the goal of the project.
