### ISSUE TITLE
read(timeout=0) not needed?

### ISSUE THREAD

**Issue by PySimpleGUI** [israel-dryer/Media-Player#10]
One of the things I'm actively scrubbing from all of my demos and documentation is any calls to read with a timeout=0.  The reason is that unless you have another call in your event loop that blocks, then you will eat up 100% of the core you are running on.  This is not being a "good corporate citizen".

Is there any particular reason to run that quickly?  Where are you feeding the data into the video player?  Is it done directly in the event loop?

I changed it to timeout=100 and saw no problems.  I even removed the timeout entirely and made the read blocking.  The only thing that changes is the progress bar updates.

So, best I can tell, the only reason the event loop is running async is to update the progress bar.  If that's the case, you can set the event loop to a much higher value, perhaps even 1000.

**Comment by israel-dryer** [comment]
I can't remember why I added the timeout=0. I think it may have been when I was taking the frame by frame approach like with the open cv program. You're right though. I just took it out and it's just fine.

**Comment by PySimpleGUI** [comment]
Thank you a billion times over!

Even with OpenCV I tend to slap a timeout=10 on there just users won't use 0.  I see a lot of programs use timeout=0 when they don't need any async at all.  Sure, it works, but it also knocks out all of the programs running on that core.  I feel responsible for teaching people responsible ways of programming... it's an entire system that's being designed and written, not just a single program or a callback function.

Anyway, I really appreciate the amount of flexibility and willingness to look at things that you show.  It's a really mature way to approach programming.  I'm doing my best to teach you and not be overly  picky in the process.  :-)

**Comment by israel-dryer** [comment]
I think I'll use `timeout=1000` so that the progress bar updates at least once a second.

**Comment by PySimpleGUI** [comment]
That's **exactly** what I would have done!  Nice job creating a really really clean loop that uses a tiny amount of resources.  It's very well done.
