### ISSUE TITLE
Closing with an X causes error to be displayed.

### ISSUE THREAD

**Issue by PySimpleGUI** [israel-dryer/Media-Player#11]
Does not seem to have an ill effect as the window is being closed.  This info is being printed on my console.

```
[0000025671ba8f90] avcodec decoder: Using D3D11VA (NVIDIA GeForce GTX 1070, vendor 4318(NVIDIA), device 7041, revision 161) for hardware decoding
[0000025672b20070] direct3d11 vout display error: SetThumbNailClip failed: 0x800706f4
```

I thought it was perhaps because the check for None was not immediately after the read.  The call to update_bar for example is illegal after the window has returned a None event in a read.  My thought was maybe the player.set_hwnd was causing it so I moved that one too as a result of shuffling things.

Here's the start of the event loop I'm running now:

```python
while True:
    event, values = window.read(timeout=None)
    if event in(None, 'Exit'):
        break
    window['TIME'].update_bar(current_count=player.get_time(), max=player.get_length())
    player.set_hwnd(h)
```

**Comment by israel-dryer** [comment]
It looks like you can remove `player.set_hwnd(h)` altogether because I'm already setting it when I create the player in the "VLC PLAYER" section. I was thinking this was required to refresh the image, but apparently not. My ignorance is showing a bit as I start experimenting beyond my expertise. But... I guess that's how you learn.

**Comment by israel-dryer** [comment]
I'm getting this error when I go from pause to play... It doesn't seem to be affecting performance. I have absolutely no error handling for buffering, etc... 
```
[000000000b576ee0] avcodec decoder error: hardware acceleration picture allocation failed
[h264 @ 000000000c609020] get_buffer() failed
[h264 @ 000000000c609020] thread_get_buffer() failed
[h264 @ 000000000c609020] decode_slice_header error
[h264 @ 000000000c609020] no frame!
```

**Comment by PySimpleGUI** [comment]
1. Is there any way to get around the finalize?

I guess I need to better understand the user of the ID that you're getting from the Widget (`h`).  Not sure what `h` is just yet and how it works.

2. Did you pick up on the fact that you do not need to specify a default image in Image elements?  Just checking to see you know the method of creating an Image Element without anything initially attached to it so that you don't need an initialization file or base64 image

**Comment by israel-dryer** [comment]
from vlc
```python
    def set_hwnd(self, drawable):
        """Set a Win32/Win64 API window handle (HWND).

        Specify where the media player should render its video
        output. If LibVLC was built without Win32/Win64 API output
        support, then this has no effects.

        @param drawable: windows handle of the drawable.
        """
        if not isinstance(drawable, ctypes.c_void_p):
            drawable = ctypes.c_void_p(int(drawable))
        libvlc_media_player_set_hwnd(self, drawable)
```

**Comment by israel-dryer** [comment]
yeah, I saw on the images where you used an empty string, which I didn't know you could do before. The `DEFAULT_IMG` I'm using in this app is the background for the application when there is no video showing... which isn't strictly necessary, but looks cool. :-)

**Comment by israel-dryer** [comment]
The bit from the VLC example I was imitating are lines 311-335. Probably would help to comment some of that or at least add a more useful variable name.
https://github.com/oaubert/python-vlc/blob/master/examples/tkvlc.py

```python
    def _Play(self, video):
        # helper for OnOpen and OnPlay
        if isfile(video):  # Creation
            m = self.Instance.media_new(str(video))  # Path, unicode
            self.player.set_media(m)
            self.parent.title("tkVLCplayer - %s" % (basename(video),))

            # set the window id where to render VLC's video output
            h = self.videopanel.winfo_id()  # .winfo_visualid()?
            if _isWindows:
                self.player.set_hwnd(h)
            elif _isMacOS:
                # XXX 1) using the videopanel.winfo_id() handle
                # causes the video to play in the entire panel on
                # macOS, covering the buttons, sliders, etc.
                # XXX 2) .winfo_id() to return NSView on macOS?
                v = _GetNSView(h)
                if v:
                    self.player.set_nsobject(v)
                else:
                    self.player.set_xwindow(h)  # plays audio, no video
            else:
                self.player.set_xwindow(h)  # fails on Windows
            # FIXME: this should be made cross-platform
            self.OnPlay()
```

**Comment by PySimpleGUI** [comment]
>  which isn't strictly necessary, but looks cool. :-)

I'm good with looking cool!  Just wanted to ensure you've got the best knowledge possible.  You're writing such good code.

Thanks for the added bit about the mysterious variable 'h' which I assume means "handle"?

**Comment by israel-dryer** [comment]
This is a little more clear on the "id". You could remove finalize by moving the out_element assignment in the while loop... but not sure if that's a good idea. Is there a reason you wanted to get around the `finalize`?

```python
# ----- VLC PLAYER ------------------------------------------------------------------------------ #
Instance = vlc.Instance()
player = Instance.media_player_new()

# set where media player should render output
out_element = window['VIDEO'].Widget.winfo_id()
player.set_hwnd(out_element)

def setup_player(player, media, window):
    media = Instance.media_new(str(media))
    player.set_media(media)
    player.play()
```

**Comment by PySimpleGUI** [comment]
Yea, `finalize` is a bit of a hack.  It creates and shows the window ahead of when it's needed.  It works outside the normal workings of the `read` cycle that happens in an event loop.  You saw the effects it had on the text input for example.  That triggered a very real hack to be put in to "Fix" that problem.

It complexes stuff up in a way.  Leaves users scratching their heads as to what it is and when they may need to call it.

I guess the answer is a 2 part one.

1. I'm like a hawk on simplicity of code written using PySimpleGUI.  I look immediately in programs for `timeout=0` and for `finalize`.  They are constructs that have their place but are easily abused
2. I don't like code that is not needed or is left over.  It's confusing.

I'm used to writing code for products so there's a weird mashup that's happening with PySimpleGUI.  My instincts for writing good production level code get mixed in with a desire to write code that is instructional and hyper-clean.  

You can be a bit more 'relaxed' about the code you post.  I need to remain hyper-vigilant with my code as one slip-up can have the effect of causing another person to spend hours looking at something.  

There is also the portability thing that drives much of this constant desire to simplify.  It's not trivial to pull off 3 operating systems, pre-3.5 and even 2.7 Python releases, running on special hardware like the Pi, and portable across 3 desktop GUI frameworks and one in-browser framework.

In short, the simpler the program, the higher the chances of success in running in those required environments.  3 OSs and 4 GUI Frameworks means 12 different combinations that a program has the potential of running on.  

I have a background in fault tolerant systems... it started with equipment that went into the phone company's  central offices and literally had that five-9's thing as a requirement.  There's been a slew of embedded systems too that had to be fault tolerant including the first slot machine in the US (or worldwide as far as I know) that was running on a Casino floor that contained a hard disk rather than just ROMs.

I think you have to get a little bit of an understanding of those decades of training and work to understand the weird and strange points of emphasis that I have.

**Comment by PySimpleGUI** [comment]
```python
out_element = window['VIDEO'].Widget.winfo_id()
```

How about this instead?  Element is kind of a taken term in PySimpleGUI and out_element is not an element best I can tell but rather a tkinter ID.

```python
video_widget_id = window['VIDEO'].Widget.winfo_id()
```

**Comment by israel-dryer** [comment]
makes sense. I'll update that.
