### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by PySimpleGUI** [israel-dryer/Media-Player#12]
I see what I think to be enough windows specific stuff that this code won't run on Linux as it is.  Is this right?

**Comment by israel-dryer** [comment]
I don't think it will run as-is. But you can make it cross-platform capable. In the original example of the python-vlc bindings, there are several examples where they are making platform dependent code adjustments.

https://github.com/oaubert/python-vlc/blob/master/examples/tkvlc.py

**Comment by israel-dryer** [comment]
Would be nice to have something other than vlc that worked for streaming that was independent of local hardware & software...

**Comment by israel-dryer** [comment]
Added a few adjust to run on my Raspberry Pi 3B+ which is running the Debian Buster distro.

![image](https://user-images.githubusercontent.com/42584742/67165507-f2a14080-f353-11e9-8074-25ce6875b50c.png)

Everything I needed to get started:
- sudo pip3 install python-vlc
- sudo pip3 install pafy
- sudo pip3 install --upgrade youtube-dl
- sudo pip3 install --upgrade pysimplegui
- sudo apt-get install vlc

**Comment by israel-dryer** [comment]
I'm still getting some errors in the background.. but it doesn't seem to affect performance, for now...
```
[6a405f80] main tls client error: cannot resolve r2---sn-5ualdn7z.googlevideo.com port 443: System error
[6a451a40] prefetch stream error: cannot seek (to offset 676266)
[6f9e9ad8] mmal_codec decoder: VCSM init succeeded: CMA
[6ad00578] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
[6af09978] mmal_xsplitter vout display error: Failed to open Xsplitter:opengles2 module
```

**Comment by israel-dryer** [comment]
Linux compatibility was added in both the mini and standard players
