### ISSUE TITLE
Comment says YouTube player... but isn't it a file and stream player?  (both)

### ISSUE THREAD

**Issue by PySimpleGUI** [israel-dryer/Media-Player#13]
In the demo I WAS creating, but will stop because yours is so much better, 

This was the description I had jotted down

>     A very simple media player ready for you to customize.  Uses the VLC player to playback local files and streams.  You will need to install the Python bindings for VLC as well as the VLC player itself. Those are easy to obtain by doing a pip installation -     pip install python-vlc

Is that a correct assessment of what it does?  (and how to pip install vlc)

**Comment by israel-dryer** [comment]
yes, you're right. should be media.

will also need to install `youtube_dl`

**Comment by PySimpleGUI** [comment]
Do you have to have youtube_dl if you only play local media?

**Comment by israel-dryer** [comment]
no, only for YouTube and some other streaming media. as far as VLC goes... **youtube_dl** is taking the supplied url and returning the real location of the file for the player to stream.

**Comment by PySimpleGUI** [comment]
BTW, you can playback a DropBox video too!

Here's how....Right click on a dropbox file and choose "Copy dropbox link"

Paste that link into the player but modify the last character.  It'll be `dl=0` change to `dl=1` and the player will play this link.

This trick works when sharing files with people on dropbox.  If you change that character, when they click on the link, it'll immediately download the file instead of taking them to the dropbox site.

![image](https://user-images.githubusercontent.com/46163555/67885732-7ca09480-fb1e-11e9-881f-025b63a17187.png)
