### ISSUE TITLE
[Suggestion] Change Submit to Load

### ISSUE THREAD

**Issue by PySimpleGUI** [israel-dryer/Media-Player#14]
Would this not be better?
```python
sg.Button('Load', key='SUBMIT')],
```

Here's what it looks like with the change.  Not the message the player displayed on the bottom (that part wasn't changed)

![image](https://user-images.githubusercontent.com/46163555/67882817-444a8780-fb19-11e9-8aa7-0f086dfc33c7.png)

**Comment by israel-dryer** [comment]
I like that. I went ahead and changed it.

I also made sure it worked on Linux. Had to make a few tweaks for compatibility, but it looks pretty good.

![image](https://user-images.githubusercontent.com/42584742/67883848-2da53000-fb1b-11e9-8ef5-cc8c3fb68e6b.png)

**Comment by PySimpleGUI** [comment]
OH WOW WOW WOW on the Linux!!
