### ISSUE TITLE
[Idea]  Button Menus instead of Menu Bar

### ISSUE THREAD

**Issue by PySimpleGUI** [israel-dryer/Media-Player#17]
Was looking at your player with this screenshot:
![image](https://user-images.githubusercontent.com/46163555/68548683-9dd67000-03bd-11ea-829e-45adcaf72bc7.png)

Because the Menu Bars are not styled in Tkinter they are going to be a color mismatch.

What you could so in stead is create button menus for each menu item.  Then you could even use a custom graphic for each one if you wanted.

Note that a Menu Bar menu definition is a list of Button Menu definitions :-) Just pick off each list from your menu definition and you'll have the individual button menus.

**Comment by israel-dryer** [comment]
I like that idea... is there any way to control the format of the sub menu when I click on the File button, for example?
![image](https://user-images.githubusercontent.com/42584742/68556390-12ca9980-0400-11ea-99c4-7fe836bae2e9.png)

**Comment by PySimpleGUI** [comment]
Format?  Do you mean the overall style?  Colors that sort of thing?

**Comment by israel-dryer** [comment]
Yes, I can change the overall style of the button itself, but the menu itself is still black on white.

**Comment by PySimpleGUI** [comment]
Were you able to do that with the menu bar?  Trying to understand if you lost functionality or are looking to add more.

**Comment by PySimpleGUI** [comment]
You could also not use buttons but graphics instead for them, distancing them from being a normal title bar and instead something else, whatever you want to call or make that.

**Comment by israel-dryer** [comment]
I decided to consolidate the two players into a single project, so I pulled various elements from each. I ended up scraping the menu altogether.
