### ISSUE TITLE
Play button doesn't match conventions

### ISSUE THREAD

**Issue by PySimpleGUI** [israel-dryer/Media-Player#3]
I understand the convention you're using for the play button.  You've got the play icon shown when it's playing.  I don't believe that's the norm is it?  I think it's supposed to be the stop button shown while playing because that's what it does.  From a UI standpoint, I think the convention is that it doesn't represent the current state but rather the operation it performs.

**Comment by israel-dryer** [comment]
good catch

**Comment by israel-dryer** [comment]
I ended up just adding a pause button on the new version. But I did fix that in version 1. So, if I end up reworking that, it will be good.
