### ISSUE TITLE
No Titlebar  + Grab Anywhere + Right click menu (to exit)

### ISSUE THREAD

**Issue by PySimpleGUI** [israel-dryer/Media-Player#4]
Just a suggestion :-)

I also did a GreenTan color scheme just for fun.

This is a HOT looking interface.

Added keep_on_top too so it doesn't get list because you don't have a taskbar icon with no_titlebar.

![image](https://user-images.githubusercontent.com/46163555/67130231-a973b400-f1ce-11e9-8415-3b615d1cf3a3.png)

**Comment by israel-dryer** [comment]
Love this. I'll need to add an exit somewhere though. I'm thinking this would be a great application for the right-click menu.

**Comment by israel-dryer** [comment]
I wanted to add a minimize function to the 'right-click' window. But for some reason it kept crashing... so I just added the title back for now.

A few adjustments  
- set all fonts to the default font (hopefully will help with cross-platform
- the thumbnail is pulling straight from the YouTube link (convert jpg to png)
- Title, Channel, and Category from the YouTube channel now replaces the Artist, Album, Track
- Added the image data from your example file

**Comment by MikeTheWatchGuy** [comment]
please  post more about your crash. There is at least one demo program that shows a button that will minimize the window. I think it is in the Mac buttons demo. It is a no title bar window with a button that minimizes the window

**Comment by MikeTheWatchGuy** [comment]
I used the screenshot yesterday in a reply to a post on Reddit where are the poster was asking " why do python GUIs look like shit?" I pointed out that this piece of art was not only made in tkinter but is a work in progress and not fully polished. The expectation seems to be that a python  program should look as good or better, with no effort, as a GUI built with a purpose-built, Mac only tool, that makes a very fancy GUI at the push of a button. these young kids with no programming experience Beyond these push button things don't seem to really understand programming, the role of a graphic design Department, and how the real world works When developing products that involve software. To them, it would appear that anything that doesn't magically and with zero effort create something is a piece of s*** it creates only f****** ugly results when in fact the responsibility lies entirely on the programmers shoulders the create something that looks good. Sorry for the profanity but these were the words and phrases that this particular poster used

**Comment by MikeTheWatchGuy** [comment]
https://www.reddit.com/r/Python/comments/djmzjn/python_gui/?utm_medium=android_app&utm_source=share

**Comment by PySimpleGUI** [comment]
Oh!  I just thought about the minimize problem you're going to have.

If you don't have a titlebar, it icon will not show up on the taskbar.

Now, if you REALLY want to get cool, crazy, you can add PySimpleGUIWx to the player.  Yes, PySimpleGUIWx and PySimpleGUI mixed.

The reason for PySimpleGUIWx is to get the SystemTray feature.  This will allow you to do a "Minimize to system tray", a really hot, advanced feeling feature.

I've done it on more than 1 project and it works great.  Sorry that PySimpleGUIWx isn't to the point the player can be run there.

Once I make some money from my patent, then I'll be able to afford to fund the completion of the ports, including the Kivy port.  Until then, we have to scrape by.

I have trained myself to stay away from these super-advanced features however.  For the code I write, I assume it needs to run on Python 3.5, on a Raspberry Pi.  That's the limit as to how fancy I can get and I also limit the PySimpleGUI calls to the primary ones so that the single-line-import is all that's required to run on 3 GUI frameworks (Wx just isn't quite there but the others are).

What I'm hoping for your stuff is that you can fork at an early point, or that you can strip way back your more advanced version, so something as a starting point for a beginner.  Like I did with OpenCV for example.  There are several demos, all are super simple and meant to give people a starting point where they do not have to remove code, but instead are as near perfectly situated to only ADD their code and they're done.  It's an "Integration" demo, not an end user demo that I seek for demo programs.  

So, think about how you can maybe make a trim, slim, shows how to integrate with VLC and then gets out of the way.  No fancy fonts other the font size, etc.  I hope you understand what I mean.

**Comment by israel-dryer** [comment]
Interesting Reddit post. yeah, not all GUI's are meant to look like works of art... functionality is the primary concern for a lot of applications. Obviously, there are lot of cases when the visual appeal is extremely important, but it all just depends on the situation. It looks like your feedback went over fairly well though.

**Comment by PySimpleGUI** [comment]
I think it should kinda do both, look great and function well.  I dunno, I've worked with production shops and maybe was spoiled working with professionals.  I shipped quite a bit of software with high production-values that functioned quite well.  Our art departments were just as large as my engineering groups.  It depended on the company, but anything with a real UI had a design group behind it.  It's a nice thing to teach engineers, make shit function well and look good.

Then again, I'm trying to drag people off the command line and onto the screen.  Python has the chance to completely take over the "win forms" style Windows applications as well as a number of other GUIs.  

I really appreciate all you do.  It's a lot of work, doing the software and dealing with me on top of that ;-)

**Comment by israel-dryer** [comment]
just tried `window['SOUND'].update(image_data = SOUND_ON if player.audio_get_mute() else SOUND_OFF)` and it worked perfect. Thanks for that recommendation... will be using that again in the future.

**Comment by israel-dryer** [comment]
works here too `window['PAUSE'].update(image_data = PAUSE_ON if player.is_playing() else PAUSE_OFF)`

**Comment by israel-dryer** [comment]
The event loop is so much cleaner now... I'm at 137 lines total now, and that's with 20 lines of comments at the head.

```python
# ----- MAIN EVENT LOOP-------------------------------------------------------------------------- #
while True:
    event, values = window.read(timeout=0)
    window['TIME'].update_bar(current_count=player.get_time(), max=player.get_length())
    player.set_hwnd(h)

    if event in(None, 'Exit'):
        break
    if event in ('STOP', 'Stop'):
        player.stop()
        window['PLAY'].update(image_data = PLAY_OFF)        
    if event in ('PLAY', 'Play'):
        player.play()
        window['PLAY'].update(image_data = PLAY_ON)
        window['PAUSE'].update(image_data = PAUSE_OFF)
        window['TIME'].update_bar(current_count=player.get_time(), max=player.get_length())
    if event == 'PAUSE':
        window['PAUSE'].update(image_data = PAUSE_ON if player.is_playing() else PAUSE_OFF)
        window['PLAY'].update(image_data = PLAY_OFF if player.is_playing() else PLAY_ON)        
        player.pause()
    if event == 'REWIND':
        player.set_position(max(0, player.get_position() - 0.02))
    if event == 'FORWARD':
        player.set_position(min(1, player.get_position() + 0.02))        
    if event in ('SOUND', 'Mute'):
        window['SOUND'].update(image_data = SOUND_ON if player.audio_get_mute() else SOUND_OFF)
        player.audio_set_mute(not player.audio_get_mute())
    if event == 'Open Stream':
        media = get_stream(window)
        if media is not None:
            setup_player(player, media, window)
    if event == 'Open File':
        media = get_local_file()
        if media is not None:
            setup_player(player, media, window)
```

**Comment by MikeTheWatchGuy** [comment]
amazing!! clean👌 love your code.

may want to move the check 4 event is none too right after the read.
It will remove a race condition
I can't imagine what a mess this would be with callbacks for all of those events and yet how almost trivial it is to read the entire logic of your player in one single block of code. There are many unexpected outcomes or features of pysimplegui that I didn't expect when it was designed. Code like yours really brings out these things and makes them really apparent. The clean code helps beginners immensely
