### ISSUE TITLE
Using expand makes code non-portable

### ISSUE THREAD

**Issue by PySimpleGUI** [israel-dryer/Media-Player#5]
Are these really needed?

```python
    window['LEFT'].expand(expand_y=True)
    window['RIGHT'].expand(expand_y=True)
```

I like that you use the fancy stuff, but going bleeding edge means non-portable.  Expand in particular will keep you firmly grounded as a tkinter-only application.

I was able to comment them out with no problem.

I also removed the column justification which you definiitely don't need because it's set to left.

I also removed `margin` from Window call.

Anyway, the result after that was that I changed the import to Qt and this ran!  THAT is bad ass.

![image](https://user-images.githubusercontent.com/46163555/67130805-7cc09c00-f1d0-11e9-9a98-65caaac0eb24.png)

**Comment by israel-dryer** [comment]
Awesome. I originally had a busier layout with a few more columns, but simplified it. But I didn't revisit the expand. I took those and the margins out and it looks great.

**Comment by israel-dryer** [comment]
Oh yeah... also added fast-forward and rewind!
