### ISSUE TITLE
Diff between ver 1 and 2

### ISSUE THREAD

**Issue by PySimpleGUI** [israel-dryer/Media-Player#7]
What would you say is the difference between the 2?

It's been incredible to watch!

Making announcement about it now!  REALLY cool!

**Comment by israel-dryer** [comment]
Thanks! Version 1 I think was just a first pass... I basically just started over from scratch. I might end up reworking it and turning it into an online radio streaming application, but we'll see. The difference is that the first version was not meant to stream video.
